### ISSUE TITLE
Error on new visualisation tool

### ISSUE THREAD

**Issue by wvdwal** [hl7-be/lab#197] opened 2023-05-30 12:45 UTC
The tool for visualization of reports has been renewed.
I tested already some reports in the old tool by uploading json files. However, in the new tool (https://fhir-testserver.be/index.php/visualization_webapp) I get with every attempt the following error:

Error: 0
Unknown Error

**Comment by bdc-ehealth** [comment] 2023-05-31 07:59
@wvdwal ,

I just tested the visualization, and for me it works ok. Can you add the file here, or  if it contains GDPR sensitive data, send it to support@be-ehealth-standards.atlassian.net , I will then investigate what is going on.

**Comment by bdc-ehealth** [comment] 2023-06-01 07:06
@wvdwal ,

I received your testfiles, validated them, and they are correct. So, no worries. I also tried the visualization tool on them, and it works fine:

![image](https://github.com/hl7-be/lab/assets/90335317/e79c71fd-f239-48b1-a89d-604f949050c3)

As the files contain only dummy test data, I will post a screenshot here:

![image](https://github.com/hl7-be/lab/assets/90335317/6a92a3d6-7d0a-46a7-a7b1-5c199aec5629)

Did you select DIGIRELAB as a project in the visualizer? I don't see any other possible misunderstandings. If the problem persists, we can set up a call.

**Comment by bdc-ehealth** [comment] 2023-06-06 12:19
@thibaultmh ,

Hi Thibault,

your file is not valid, but it does display in the visualizer, I paste a screenshot below:

![image](https://github.com/hl7-be/lab/assets/90335317/92536370-ef79-49ab-bc78-5ac77b83e72b)

**Comment by sebwautelet** [comment] 2023-06-12 07:21
@bdc-ehealth I have the same "Unknown Error" when accessing the tool through a proxy, but it works fine with a direct connection.

This error shows up in Chrome's console when accessing the tool through a proxy : 

Access to XMLHttpRequest at 'https://fhir-visualisation-api.be/rest/fhir/r4/viz/lab/html/validate' from origin 'https://fhir-testserver.be' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by bdc-ehealth** [comment] 2023-06-12 07:45
@sebwautelet ,

Thank you for the information, we will try to fix this!

@jmp-ehealth

**Comment by bdc-ehealth** [comment] 2023-07-04 12:53
@sebwautelet ,

we have some problems reproducing the issue. Could you please send us following screenshots from the validate PREFLIGHT request/response?

![2023-07-04_14h51_06](https://github.com/hl7-be/lab/assets/90335317/01836caf-2ef3-419e-8877-c7d4e471866e)

![2023-07-04_14h51_30](https://github.com/hl7-be/lab/assets/90335317/9c5fa7ae-a464-448b-8e62-a93d390972dc)

**Comment by sebwautelet** [comment] 2023-07-04 13:40
@bdc-ehealth 
![image](https://github.com/hl7-be/lab/assets/136067382/ce124546-704f-418d-9fc3-75cec8cd4db0)
![image](https://github.com/hl7-be/lab/assets/136067382/942cf803-d6e4-41af-8e52-77ce20015151)

It seems that our proxy redirects (HTTP 303) to a warning page because fhir-visualisation-api.be is not whitelisted, I've asked our admin to do it.

**Comment by bdc-ehealth** [comment] 2023-07-04 14:39
@sebwautelet thanks for the update.

**Comment by bdc-ehealth** [comment] 2023-07-04 14:39
@thibaultmh : can you provide similar screenshots, the way Sébastien did?

**Comment by thibaultmh** [comment] 2023-07-07 09:16
I have a 403

![afbeelding](https://github.com/hl7-be/lab/assets/86883419/6a11971e-f961-4986-a28b-8f76b9c1b9ff)

**Comment by bdc-ehealth** [comment] 2023-07-07 09:56
@thibaultmh That is strange... You do not have a preflight check? If you look at the other screenshots, you can see there are two validate calls, on a preflight (OPTIONS) - call, and then the POST. You only have the POST.

**Comment by thibaultmh** [comment] 2023-07-07 14:10
@bdc-ehealth I don't know anything about that. However, I think it might have something to do with our VPN, because without it I can validate. I will raise an internal incident for our IT service.

**Comment by sebwautelet** [comment] 2023-07-11 10:53
The visualisation tool now works correctly for me after whitelisting fhir-visualisation-api.be in our proxy.

**Comment by bdc-ehealth** [comment] 2023-07-11 11:38
@sebwautelet Thank you for your feedback. I will close the issue now.

**Closed by bdc-ehealth** 2023-07-11 11:38 UTC
